### ISSUE TITLE
Use without xcode

### ISSUE THREAD

**Issue by racemus** [mitchdzugan/osx-wiiu-gcc-adapter#1]
Hi.
Is it possible to use it without xcode? Like just install kext in S/L/E ?

**Comment by mitchdzugan** [comment]
Probably, I don't have osx on any of my computers at the moment so i cant do much with this right now. I'd check this fork tho (https://github.com/area/osx-wiiu-gcc-adapter) I think this guy has it working as a clean install without xcode

**Comment by racemus** [comment]
Thanks! I'll try it.

**Comment by racemus** [comment]
It works on my El Capitan. Thanks!
